/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.firstproject;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        int i = 5;
        System.out.println(i);
        if (i < 1) {
            System.out.println("inside if");
        }
        System.out.println(i);
    }
}
